### ISSUE TITLE
RoundRobinLoadBalancerFactory

### ISSUE THREAD

**Issue by kiril-me** [lightstep/lightstep-tracer-java-common#103]
RoundRobinLoadBalancerFactory was removed since GRPC v1.21, but still used by lightstep in:

https://github.com/lightstep/lightstep-tracer-java-common/blob/master/grpc/src/main/java/com/lightstep/tracer/shared/GrpcCollectorClientProvider.java

The workaround is to shutdown it off:
```
new Options.OptionsBuilder().withGrpcRoundRobin(false)
```

`ManagedChannelBuilder .defaultLoadBalancingPolicy` should support `round_robin`. By default it's is `pick_first`.

**Comment by carlosalberto** [comment]
Closed as #104 was merged ;)
