### ISSUE TITLE
Collisions in `generateRandomGUID`

### ISSUE THREAD

**Issue by drewrobb** [lightstep/lightstep-tracer-java-common#117]
The initial value method https://github.com/lightstep/lightstep-tracer-java-common/blob/0.19.2/common/src/main/java/com/lightstep/tracer/shared/Util.java#L24 has a bug. The term `(long) (1024 * Math.random()))` will be exactly 0 about 1/1024th of the time. As these arguments are multiplied together, the final seed will also be 0 about 1/1024th of the time. This means that 1/1024 threads will generate the exact same sequence of trace/span ids, so collisions will start to appear once you combine tracing data from a sufficient number of threads.

We observed this in production-- one of the duplicated span ids was `78191ceded172f2`. One can demonstrate that this exact span id comes from a 0 seeded `java.util.Random` and thus this bug is the source of our collisions: 
```
val r = new java.util.Random(0) 
Range(0, 1000000).foreach{ i => 
  val id = java.lang.Long.toHexString(r.nextLong()) 
  if (id == "78191ceded172f2") println(i) 
}
```
(outputs 774)

There are a bunch of ways to fix this:

I would suggest not multiplying these terms together-- even without this bug, there are other ways in which multiplying together random numbers with overflow looses bits of entropy. For example, each term that is even will result in another bit that is always even. Instead, it would be best to hash them together, using a hash function with at least 64 bits of state. Something like a 128bit murmur3 hash is probably good: https://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/digest/MurmurHash3.html#hash128-byte:A-.

Furthermore, java.util.Random itself only has 48bits of internal state (https://docs.oracle.com/javase/8/docs/api/java/util/Random.html) and is probably not ideal for this application, as it would also cause collisions eventually more frequently than is possible. A RNG that has more than 64bits of internal state and that has the property of eventually generating all 64bit values would be ideal. I think https://commons.apache.org/proper/commons-math/javadocs/api-3.3/org/apache/commons/math3/random/MersenneTwister.html  has these properties, but I am not an expert.

**Comment by peteroupc** [comment]
Java already has an ID generator: the `randomUUID` method of `java.util.UUID`.

**Comment by malafeev** [comment]
I don't understand why `ThreadLocalRandom` is not used, something like `ThreadLocalRandom.current().nextLong(10, Long.MAX_VALUE);` 
seed is using thread id therefore should be enough to avoid collisions between threads.

**Comment by spkrka** [comment]
Agreed, ThreadLocalRandom would be better. I have an intermediate PR here, that doesn't replace it with ThreadLocalRandom but at least combines the different seed inputs in a better way: #153

**Comment by malafeev** [comment]
thanks @spkrka, let's close it for now and reopen if still see collisions.
