### ISSUE TITLE
Crash when creating a span asChildOf a NoopSpanContext

### ISSUE THREAD

**Issue by spiliopoulos** [lightstep/lightstep-tracer-java-common#118]
It seems that the lightstep tracer is not behaving consistently when handling entities from `io.opentracing.noop`. 

For example it will sanely do nothing when asked to activate a `NoopSpan` with `tracer.activateSpan(span)` (mainly because its delegated to the `io.opentracing` implementation of a `scopeManager`) but when asked to create a span with a `childOf` relationship to a `NoopSpan` with `tracer.buildSpan("foo").asChildOf(noopSpan)` it throws an exception since it's unable to cast a `NoopSpanContext` to a `com.lightstep.tracer.shared.SpanContext` as you can see in the linked fragment below

https://github.com/lightstep/lightstep-tracer-java-common/blob/9e6af9fd727236910d64431e18e69d9a8c33ddca/common/src/main/java/com/lightstep/tracer/shared/SpanBuilder.java#L55

We should be consistent and handle Noop flavors of the opentracing entities gracefully. The motivation for that is that some logic might query the NoopTracer before we get a change to register our own implementation, and then try to use that with our own implementation after registration.

**Comment by carlosalberto** [comment]
I don't think it's a common (nor recommendable) thing to be mixing no-op `Span`s but I do agree we should keep the unexpected error at a minimum. Will cook a PR to solve this and will do a release by the end of this week ;)

**Comment by spiliopoulos** [comment]
Thank you. If PRs are welcome I can try to get a PR out to.
