### ISSUE TITLE
Exception not fully correctly logged

### ISSUE THREAD

**Issue by plum117** [lightstep/lightstep-tracer-java-common#144]
Hi,

When some exceptions are throwned, they are sometimes logged using the `com.lightstep.tracer.jre.JRETracer` using `LOGGER.error(s);` where s is a string. Doing so when logging an Exception can lead to some missing information contained in the Exception.

Normally, when logging an exception using log4j we use `LOGGER.error(string, exception);`

I had some trouble with Tracing not being sent to the collector and the error I was seeing was (with no stack trace) : 

> Status runtime exception (likely malformed spans):  io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

After overriding the class and add a proper logging with the exception then I was able to see and understand my problem:

> message | Error in GrpcCollectorClient:UNAVAILABLE: io exception
> thrown.class | io.netty.handler.ssl.NotSslRecordException
> thrown.message | not an SSL/TLS record: 485454502f312e31203430302042616420526571756573740d0a636f6e74656e742d6c656e6774683a20300d0a636f6e6e656374696f6e3a20636c6f73650d0a0d0a
> thrown.stacktrace | {   "classLoaderName": null,   "moduleName": null,   "moduleVersion": null,   "methodName": "decodeJdkCompatible",   "fileName": "SslHandler.java",   "lineNumber": 1198,   "className": "io.netty.handler.ssl.SslHandler",   "nativeMethod": false }, {   "classLoaderName": null,   
> ....

My problem was sending the information to https while it should have been http.

Therefore to enhance troubleshooting, I would like to suggestion to change `com.lightstep.tracer.jre.JRETracer#printLogToConsole`

To be something like (code could be shrinked in a better way) :

```
    protected void printLogToConsole(InternalLogLevel level, String msg, Object payload) {
        String s = msg;
        if (payload != null) {
            s += " " + payload.toString();
        }
        
        if(payload instanceof Exception)
        {
            switch (level) {
                case DEBUG:
                    LOGGER.debug(s, payload);
                    break;
                case INFO:
                    LOGGER.info(s, payload);
                    break;
                case WARN:
                    LOGGER.warn(s, payload);
                    break;
                case ERROR:
                    LOGGER.error(s, payload);
                    break;
            }
        }
        else {
            switch (level) {
                case DEBUG:
                    LOGGER.debug(s);
                    break;
                case INFO:
                    LOGGER.info(s);
                    break;
                case WARN:
                    LOGGER.warn(s);
                    break;
                case ERROR:
                    LOGGER.error(s);
                    break;
            }
        }
    }
```
What do you think?

**Comment by malafeev** [comment]
created PR in tracer-java-common: https://github.com/lightstep/lightstep-tracer-java-common/pull/149
after it will be merged and tracer-java-common released this issue can be fixed.

**Comment by malafeev** [comment]
done

**Comment by plum117** [comment]
Tx
