### ISSUE TITLE
There is no way to set deadlineMillis

### ISSUE THREAD

**Issue by malafeev** [lightstep/lightstep-tracer-java-common#35]
`deadlineMillis` is always equal `DEFAULT_DEADLINE_MILLIS = 30000;`

I often get error:
`Collector response contained error:  <ByteString@1c07bbd4 size=77>`
So I would like to tune tracer to find root cause.

**Comment by carlosalberto** [comment]
This feature has been supported for some time now. @malafeev feel free to re-open this issue if I'm wrong ;)
