### ISSUE TITLE
Missing inferred child_of relationship between parent ActiveSpan

### ISSUE THREAD

**Issue by linsea** [lightstep/lightstep-tracer-java-common#37]
According to the opentracing java API:

        /**
         * Returns a newly started and activated {@link ActiveSpan}.
         *
         * <p>
         * The returned {@link ActiveSpan} supports try-with-resources. For example:
         * <pre><code>
         *     try (ActiveSpan span = tracer.buildSpan("...").startActive()) {
         *         // (Do work)
         *         span.setTag( ... );  // etc, etc
         *     }  // Span finishes automatically unless deferred via {@link ActiveSpan#capture}
         * </code></pre>
         *
         * <p>
         * If
         * <ul>
         * <li>the {@link Tracer}'s {@link ActiveSpanSource#activeSpan()} is not null, and
         * <li>no <b>explicit</b> references are added via {@link SpanBuilder#addReference}, and
         * <li>{@link SpanBuilder#ignoreActiveSpan()} is not invoked,
         * </ul>
         * ... then an inferred {@link References#CHILD_OF} reference is created to the
         * {@link ActiveSpanSource#activeSpan()}'s {@link SpanContext} when either
         * {@link SpanBuilder#startManual()} or {@link SpanBuilder#startActive} is invoked.
         *
         * <p>
         * Note: {@link SpanBuilder#startActive()} is a shorthand for
         * {@code tracer.makeActive(spanBuilder.startManual())}.
         *
         * @return an {@link ActiveSpan}, already registered via the {@link ActiveSpanSource}
         *
         * @see ActiveSpanSource
         * @see ActiveSpan
         */
        ActiveSpan startActive();

**Comment by linsea** [comment]
https://github.com/lightstep/lightstep-tracer-java-common/blob/51ac7aa761bc7d8c743ed8a447a483fbc53aa94a/common/src/main/java/com/lightstep/tracer/shared/SpanBuilder.java#L168

it seems to adding `child of` reference at this line.

**Comment by andrewhsu** [comment]
activespan is gone
