### ISSUE TITLE
Span.log can cause a NullPointerException

### ISSUE THREAD

**Issue by mvalkon** [lightstep/lightstep-tracer-java-common#42]
In case the mapping of keys and values passed to the log method contains a null value, calling [`inValue.toString()`](https://github.com/lightstep/lightstep-tracer-java-common/blob/master/common/src/main/java/com/lightstep/tracer/shared/Span.java#L135) will cause a `NullPointerException`.

It would make sense to add a null check before calling `toString()` to avoid throwing up.

**Comment by carlosalberto** [comment]
This was fixed as part of our 0.17.1 release. Closing, thanks!
