### ISSUE TITLE
Options CollectorProtocol constants incorrectly package private?

### ISSUE THREAD

**Issue by danielbryantuk** [lightstep/lightstep-tracer-java-common#58]
Hi, 

When experimenting with the [OpenTracing example](https://github.com/opentracing-contrib/java-opentracing-walkthrough) I ran into the issue of the tracer initialisation com.lightstep.tracer.shared.Options class (via OptionsBuilder) using HTTPS by default for the collector protocol. 

Although this makes sense (from a security perspective), when I tried to override this configuration new Options.OptionsBuilder().withCollectorProtocol(String protocol) I realised that I didn't know what value to specify. I looked into the source code, and realised this had to be lowercase "http". I also found a constant ['HTTP'](https://github.com/lightstep/lightstep-tracer-java-common/blob/master/common/src/main/java/com/lightstep/tracer/shared/Options.java#L61) in this class, but this is package private?

Would you be open to a pull request that modified the two protocol constants here to be public?

**Comment by danielbryantuk** [comment]
On a related note, I also didn't see any Exceptions thrown when the original HTTPS communication to the collector endpoint was presumedly failing. 

I'm not 100% sure this isn't being swallowed by the OpenTracing example, and so is more of an FYI. 

An Exception pointing me in the direction of an incorrect URI (with the protocol and full path) would have been very helpful

**Comment by MatthewDolan** [comment]
Making those constants available sounds like a good idea to me. We could definitely accept a pull request to make those constants public.

As to your second question, which transport (`tracer-okhttp` or `tracer-grpc`) and tracer (android or java) were you using? Both transports catch exceptions and log those exceptions to the tracer logging interface. Which I think can be configured depending on which actual tracer implementation you are using (java vs android). One thing that might have been causing you an issue is the "verbosity" of the logger. It defaults to log the first error only (`VERBOSITY_FIRST_ERROR_ONLY`) which logs out the first error and fails silently on subsequent errors.

If you increase the verbosity to say, log every error (`VERBOSITY_ERRORS_ONLY`) do you see the errors you are expecting?
