### ISSUE TITLE
Upgrade opentracing-java to v0.32.0

### ISSUE THREAD

**Issue by jayeve** [lightstep/lightstep-tracer-java-common#89]
I noticed there's already a [branch](https://github.com/lightstep/lightstep-tracer-java-common/compare/ot_v0.32.0) with most of the needful updates to use [opentracing-java v0.32.0](https://medium.com/opentracing/opentracing-java-0-32-released-a3c9b6af08e4). @carlosalberto would you be interested in opening that as a PR? I'd be happy to take it across the finish line if not.

**Comment by austinlparker** [comment]
We added support for OpenTracing Java 0.32.0 in the 0.17 release of java-common. Please reopen this issue if you're having an issue with it, thanks!
